id: I674D9A29
legacy_id: P000308
ocr_import_info:
  bdrc_scan_id: W1KG13792
  source: bdrc
  ocr_info:
    timestamp: '2020-03-12T08:06:48'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T04:55:31.855974+00:00'
last_modified: 2022-08-27 12:55:42.053171
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG13792
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG13792
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྡོ་རིང་པཎྜི་ཏ་བསྟན་འཛིན་དཔལ་འབྱོར་ལགས་ཀྱི་སྐུ་ཚེའི་ལོ་རྒྱུས་དང་། གཞས་ཚིག་ཕྱོགས་བསྡུས་དགའ་བའི་གླུ་དབྱངས།
  author: བསྟན་འཛིན་དཔག་བསམ།
statistics: null
quality: null
bases:
  I1KG15371:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15371
      total_pages: 190
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG15371.txt
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
