id: opecha:P000308
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13792
  title: རྡོ་རིང་པཎྜི་ཏ་བསྟན་འཛིན་དཔལ་འབྱོར་ལགས་ཀྱི་སྐུ་ཚེའི་ལོ་རྒྱུས་དང་། གཞས་ཚིག་ཕྱོགས་བསྡུས་དགའ་བའི་གླུ་དབྱངས།
  volume: ''
  author: ''
