id: P000308
initial_creation_type: ocr
created_at: 12/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG13792
  title: རྡོ་རིང་པཎྜི་ཏ་བསྟན་འཛིན་དཔལ་འབྱོར་ལགས་ཀྱི་སྐུ་ཚེའི་ལོ་རྒྱུས་དང་། གཞས་ཚིག་ཕྱོགས་བསྡུས་དགའ་བའི་གླུ་དབྱངས།
  author: ''
  volumes:
    4a4da23a81b64689add3317ce957225f:
      image_group_id: I1KG15371
      title: Volume 1 of bod gangs can ljongs kyi gna' bo'i srol rgyun gyi sgyu rtsal
        nang ma dang / stod gzhas gnyis gsar gtod mdzad mkhan rdo ring paN+Di ta bstan
        'dzin dpal 'byor lags kyi sku tshe'i lo rgyus dang / gzhas tshog phyogs bsdus
        dga' ba'i glu dbyangs/
      volume_number: 1
      total_pages: 190
      base_file: v001.txt
